name: Test Workflow
on: push
jobs:
  test:
    name: Hello Job
    steps:
      - name: Say Hello $TEST
        run: echo "$TEST from gh-git-action-cli!"
  test2:
    name: Hello2 Job
    steps:
      - name: Say Hello
        run: |
          echo "Hello from gh-git-action-cli!"
          echo "This is the second job."
